server:
  servlet:
    context-path: /airNUR
  port: ${PORT:8082}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/Reserva"
    username: postgres
    password: root
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
        ddl-auto: create-drop

spring-doc:
  swagger-ui:
    path: /
